version: '3'
# declaring the version

services:
  backend:
    # giving a name to our service
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-19-feb-2022/final-capstone-projects/data-visualisation:master
    # specifying which image
    env_file:
      - ./env/prod.env
    volumes:
      - static-files:/static-files
#      - media-files:/media-files
      - build:/frontend/build
    command: 'sh /scripts/run.sh'
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - ./env/prod.env

    volumes:
      - postgres_db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static-files:/static-files
#      - media-files:/media-files
#      - /etc/letsencrypt:/etc/letsencrypt
      - build:/build


volumes:
  postgres_db:
  static-files:
#  media-files:
  build:
