name: final_project_data_visualisation

dependencies:
  - python==3.10
  - psycopg2==2.8.6
  - pip
  - pip:
    - django==4.0.3
    - djangorestframework==3.13.1
    - drf-yasg==1.20.0
    - django-model-utils==4.2.0

